config/routes.rb
Rails.application.routes.draw do
  devise_for :client_staffs, controllers: {
    confirmations:      'client_staffs/confirmations',
    passwords:          'client_staffs/passwords',
    registrations:      'client_staffs/registrations',
    sessions:           'client_staffs/sessions',
    unlocks:            'client_staffs/unlocks'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"

  resources :listings, only: %i[index show]
  resources :foods, only: %i[index show]

  namespace :mypage do
    resources :listings
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/shared/_errors.html.erb
<% if resource&.errors&.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button class="close" aria-label="Close" data-dismiss="alert" type="button">
      <span aria-hidden="true">x</span>
    </button>
    <% resource.errors.full_messages.each do |message| %>
      <ul>
        <li><%= message %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <!-- <div class="pd-80">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-12 mt-md-0 mt-3">
          <div class="footer-logo">
            <%= image_tag "logo.png" %>
          </div>
          <p class="footer-txt">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio excepturi nam totam sequi, ipsam consequatur repudiandae libero illum.</p>
        </div>
        <div class="col-lg-3 col-md-12 mt-md-0 mt-3 accordion">
          <ul class="nav flex-column">
            <li class="nav-item">
              <div class="footer-list-ttl d-flex align-items-center">
                <div>Helpful Links</div>
                <button class="btn btn-link col text-right" data-target="#collapse-menu1" data-toggle="collapse">
                  <i class="lg-block fas fa-chevron-down"></i>
                </button>
              </div>
              <ul id="collapse-menu1" class="collapse d-lg-block footer-list list-unstyled">
                <li><a href="" class="nav-link">Login</a></li>
                <li><a href="" class="nav-link">My Account</a></li>
                <li><a href="" class="nav-link">Add Listing</a></li>
                <li><a href="" class="nav-link">Privacy Policy</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-12 mt-md-0 mt-3 accordion">
          <ul class="nav flex-column">
            <li class="nav-item">
              <div class="footer-list-ttl d-flex align-items-center">
                <div>Category</div>
                <button class="btn btn-link col text-right" data-target="#collapse-menu2" data-toggle="collapse">
                  <i class="lg-block fas fa-chevron-down"></i>
                </button>
              </div>
              <ul id="collapse-menu2" class="collapse d-lg-block footer-list list-unstyled">
                <li><a href="" class="nav-link">Shop</a></li>
                <li><a href="" class="nav-link">Travel</a></li>
                <li><a href="" class="nav-link">Sport</a></li>
                <li><a href="" class="nav-link">Restaurant</a></li>
              </ul>
            </li>
          </ul>
        </div>
        <div class="col-lg-3 col-md-12 mt-md-0 mt-3 accordion">
          <ul class="nav flex-column">
            <li class="nav-item">
              <div class="footer-list-ttl d-flex align-items-center">
                <div>Contact us</div>
                <button class="btn btn-link col text-right" data-target="#collapse-menu3" data-toggle="collapse">
                  <i class="lg-block fas fa-chevron-down"></i>
                </button>
              </div>
              <ul id="collapse-menu3" class="collapse d-lg-block footer-list list-unstyled">
                <li><i class="fas fa-map-marker-alt"></i> 13th North Ave, Florida, USA</li>
                <li><a href=""><i class="fas fa-envelope"></i> info@listagram.com</a></li>
                <li><i class="fas fa-phone"></i> +44 078 767 595</li>
                <ul class="footer-social-btns list-unstyled">
                  <li class="list-inline-item"><a href=""><i class="fab fa-facebook-f"></i></a></li>
                  <li class="list-inline-item"><a href=""><i class="fab fa-twitter"></i></a></li>
                  <li class="list-inline-item"><a href=""><i class="fab fa-pinterest"></i></a></li>
                  <li class="list-inline-item"><a href=""><i class="fab fa-youtube"></i></a></li>
                  <li class="list-inline-item"><a href=""><i class="fab fa-dribbble"></i></a></li>
                </ul>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div> -->
  <!-- <hr class="w-100">
  <div class="container">
    <div class="footer-bottom">
      <div class="row align-items-center">
        <div class="col-lg-6 text-md-right">
          <ul class="text-side">
            <li class="list-inline-item"><a href="">Terms &amp; Condition</a></li>
            <li class="list-inline-item"><a href="">Privacy Policy</a></li>
            <li class="list-inline-item"><a href="login.html">Login</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div> -->
  <hr class="w-100">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2 text-center">
          <p>&copy; 2020 def.inc All Rights Reserved.</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_footer.html.haml
%footer#footer{"data-v-6bf351f6" => ""}
  .inner{"data-v-6bf351f6" => ""}
    /
      <nav data-v-6bf351f6="" class="upper">
      <div data-v-6bf351f6="" class="contents">
      <p data-v-6bf351f6="">CONTENTS</p>
      <div data-v-6bf351f6="" class="link"><a data-v-6bf351f6="" href="/teriyakist/" class="">
      一覧
      </a> <a data-v-6bf351f6="" href="/columns/" class="">
      コラム
      </a> <a data-v-6bf351f6="" href="/ranking/1" class="">
      ランキング
      </a> <a data-v-6bf351f6="" href="/newopen/" class="">
      新規OPEN店舗
      </a>
      </div>
      </div>
      <div data-v-6bf351f6="" class="user">
      <p data-v-6bf351f6="">USER</p>
      <div data-v-6bf351f6="" class="link">
      <a data-v-6bf351f6="" href="/user/registration" class="">
      会員登録
      </a><a data-v-6bf351f6="" href="/user/settings" class="">
      設定
      </a> <a data-v-6bf351f6="" href="/info" class="">
      お知らせ
      </a> <a data-v-6bf351f6="" href="/favorite/1" class="">
      行った/行きたい
      </a>
      </div>
      </div>
      </nav>
    %nav.lower{"data-v-6bf351f6" => ""}
      /
        <ul data-v-6bf351f6="">
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/about_us/concept" class="">
        TERIYAKIとは
        </a>
        </li>
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/about_us/deal" class="">
        特定商取引法に基づく表示
        </a>
        </li>
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/inquire/contact" class="">
        お問合せ
        </a>
        </li>
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/about_us/fq" class="">
        よくある質問
        </a>
        </li>
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/about_us/term" class="">
        利用規約
        </a>
        </li>
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/about_us/privacy" class="">
        プライバシーポリシー
        </a>
        </li>
        <li data-v-6bf351f6=""><a data-v-6bf351f6="" href="/about_us/cancel" class="">
        有料サービスの解約について
        </a>
        </li>
        </ul>
    %small.copyright ©2020 def.inc, ALL RIGHTS RESERVED

app/views/shared/_header.html.erb
<header class="header">
  <div class="container">
    <nav class="navbar navbar-expand-lg hamburger-menu">
      <%= link_to :root, class: "navbar-brand" do %>
        <h1><%= image_tag 'iwate_takeout.png' %></h1>
      <% end %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="レスポンシブ・ナビゲーションバー">
      <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
      </button>
      <div class="collapse navbar-collapse text-right" id="Navber">
        <ul class="navbar-nav mx-auto mt-2 mt-lg-0">
        </ul>

        <div class="my-2 my-lg-0">
          <div class="dd-header dropdown float-left">
            <%= link_to "【いわていくあうと】とは？", page_path('about'), class: "btn p1" %>
            <%= link_to "お問い合わせ", "https://forms.gle/swa8kjGTCskRL2gv9", class: "btn p1" %>
            <%= link_to "掲載店登録", new_mypage_listing_path, class: "btn p1" %>
          </div>
        </div>

        <% if false %>
          <div class="my-2 my-lg-0">
            <div class="dd-header dropdown float-left">
              <% if client_staff_signed_in? %>
                <%= link_to "リスティング一覧", mypage_listings_path, class: "btn p1" %>
                <%= link_to "リスティング登録", new_mypage_listing_path, class: "btn p1" %>
                <%= link_to "ログアウト", destroy_client_staff_session_path, method: :delete, class: "btn p1" %>
              <% else %>
                <%= link_to "【いわていくあうと】とは？", page_path('about'), class: "btn p1" %>
                <%= link_to "お問い合わせ", "https://forms.gle/swa8kjGTCskRL2gv9", class: "btn p1" %>
                <%= link_to "掲載店ログイン", new_client_staff_session_path, class: "btn p1" %>
                <%= link_to "掲載店登録", new_mypage_listing_path, class: "btn p1" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </nav>
  </div>
</header>

app/views/shared/_header.html.haml
%header
  .inner.clearfix
    %h1
      いわてのテイクアウト＆デリバリー情報サイト【いわていくあうと】

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to "いわていくあうと", :root, class: "navbar-brand"
  %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav
      %li.nav-item.active
        = link_to "戻る", :root, class: "nav-link"