config/routes.rb
Rails.application.routes.draw do
  devise_for :client_staffs, controllers: {
    confirmations:      'client_staffs/confirmations',
    passwords:          'client_staffs/passwords',
    registrations:      'client_staffs/registrations',
    sessions:           'client_staffs/sessions',
    unlocks:            'client_staffs/unlocks'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"

  resources :listings, only: %i[index show]
  resources :foods, only: %i[index show]

  namespace :mypage do
    resources :listings
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Listing.published.ransack(params[:q])
    @foods = Food.joins(:listing).where("listings.published = ?", true).order(id: :desc)
    @menus = Menu.joins(:listing).where("listings.published = ?", true).order(id: :desc)
    @listings = Listing.page(params[:page])

    if params[:page]
      redirect_to listings_path(page: params[:page])
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="mv" style="background-image: url(<%= asset_path 'iwate2.jpg' %>)">
  <div class="overlay opc-3"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>テイクアウトできる飲食店を探しましょう</h2>
        <h2>掲載費無料！</h2>
        <h2>掲載件数: <%= Listing.published.count %>件</h2>
      </div>
      <div class="col-md-12 text-center mt-30">
        <%= search_form_for @q, url: listings_path, class: "mv-form bg-white" do |f| %>
          <div class="row">
            <div class="col-lg-8 col-md-12">
              <div class="mv-form-row border-bottom">
                <%= f.collection_select :city_id_eq, City.joins(:listings).distinct.order(:id), :id, :name, { include_blank: "市町村を選択してください" }, class: "mv-input custom-select" %>
              </div>
            </div>
            <div class="col-lg-3 col-md-12">
              <div class="submit_btn text-right md-left">
                <%= button_tag type: 'submit', class: "btn p1" do %>
                  <i class="fas fa-search"></i> 検索
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row pd-80">
    <div class="col-md-8 offset-md-2 text-center">
      <h2 class="section-ttl">コロナに負けるな！みちのく繋がるプロジェクト！</h2>
      <h2 class="section-ttl">
        <%= link_to "https://mitinokutunagaru.seesaa.net/article/474470463.html?fbclid=IwAR3YOgxZVnTblT9RZDIwvLx7J1mf7xdi", target: "_blank" do %>
          <%= image_tag "support_project.jpg" %>
        <% end %>
         <%= link_to listings_path(q: {support_project_eq: true}), class: "btn p1", target: "_blank" do %>
           コロナに負けるな！みちのく繋がるプロジェクト！対象店舗を検索
         <% end %>
      </h2>
    </div>
</div>

<div class="container">
  <div class="row pd-80">
    <div class="col-md-8 offset-md-2 text-center">
      <h2 class="section-ttl">お店一覧</h2>
    </div>

    <% @listings.each do |listing| %>
      <div class="d-flex col-md-4">
        <div class="card">
          <%= link_to listing do %>
            <div class="place-img">
              <%= image_tag listing.image_url_or_main_image, class: "listing-main-image" %>
            </div>
          <div class="card-bottom">
            <div class="shop-name">
              <%= listing.title_with_suspension_information %>
            </div>
            <div class="shop-location-wrapper">
              <div class="shop-location"><i class="fas fa-map-marker-alt"></i><%= listing.full_address %></div>
            </div>
            <% if listing.tel %>
              <div class="shop-location-wrapper">
                <div class="shop-location">
                  <%= link_to  "tel:#{listing.tel.delete('-')}" do %>
                    <i class="fas fa-phone"></i><%= listing.tel %>
                  <% end %>
                </div>
              </div>
            <% end %>
            <div class="shop-location-wrapper">
              <%= link_to "編集する", edit_mypage_listing_path(listing), class: "btn p1" %>
            </div>
            <div class="shop-bottom d-flex border-top">
              <% if listing.support_project? %>
                <div class="shop-icon">
                  <span class="shop-icon-bg shop-icon-bg-yellow">
                    <i class="fas fa-ticket-alt"></i>
                  </span>
                  応援きっぷ対象店舗
                </div>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @listings, window: 1 %>
</div>

<div class="container">
  <div class="row pd-80">
    <div class="col-md-8 offset-md-2 text-center">
      <h2 class="section-ttl">商品一覧</h2>
    </div>

    <% @foods.each do |food| %>
      <div class="col-md-4">
        <div class="card">
          <%= link_to food.listing do %>
          <div class="place-img">
              <%= image_tag food.image_url_or_main_image, class: "listing-main-image" %>
            </div>
            <div class="card-bottom">
              <div class="shop-name">
                <%= food.listing.title %>
              </div>
              <div class="shop-location-wrapper">
                <div class="shop-location"><%= food.name %></div>
              </div>
              <div class="shop-location-wrapper">
                <div class="shop-location"><%= number_to_currency food.price %></div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row pd-80">
    <div class="col-md-8 offset-md-2 text-center">
      <h2 class="section-ttl">メニュー表一覧</h2>
    </div>

    <% @menus.each do |menu| %>
      <div class="col-md-4">
        <div class="card">
          <%= link_to menu.listing do %>
            <div class="place-img">
              <%= image_tag menu.image_url_or_image, class: "listing-main-image" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row pd-80">
    <div class="col-md-8 offset-md-2 text-center">
      <h2 class="section-ttl">各種情報サイトリンク</h2>
      <h2 class="section-ttl">
         <%= link_to "instagram #盛岡テイクアウト", "https://www.instagram.com/explore/tags/%E7%9B%9B%E5%B2%A1%E3%83%86%E3%82%A4%E3%82%AF%E3%82%A2%E3%82%A6%E3%83%88/", class: "btn p1", target: "_blank" %>
      </h2>
    </div>
    <div class="col-md-8 offset-md-2 text-center">
      <h2 class="section-ttl">
        <div id="fb-root"></div>
          <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v6.0&appId=109186586435604&autoLogAppEvents=1"></script>
          <div class="fb-group" data-href="https://www.facebook.com/groups/675319939950647" data-width="280" data-show-social-context="true" data-show-metadata="false"></div>
      </h2>
    </div>
  </div>
</div>

app/views/home/index.html.haml
%section#top.container
  #content{"data-v-48728145" => ""}
    #new-appear{"data-v-48728145" => ""}
    #article{"data-v-48728145" => ""}
      .inner.clearfix{"data-v-48728145" => ""}
        #teriyaki{"data-v-48728145" => "", "data-v-79b2de20" => ""}
          %h3{"data-v-79b2de20" => ""} TERIYAKIコラム
          .list{"data-v-79b2de20" => ""}
            %ul{"data-v-79b2de20" => ""}
              - @listings.each do |listing|
                %li{"data-v-79b2de20" => ""}
                  %a{"data-v-79b2de20" => "", :href => listing_path(listing)}
                    .thumb{"data-v-79b2de20" => ""}
                      - if listing.image.attached?
                        = image_tag url_for(listing.image)
                      - else
                        = image_tag asset_path("no_image.png")
                    .detail{"data-v-79b2de20" => ""}
                      %p.title{"data-v-79b2de20" => ""}
                        = listing.name
                      %p.text{"data-v-79b2de20" => ""}
                        = listing.description&.truncate(30)
                      %p.date{"data-v-79b2de20" => ""}
                        = listing.created_at.strftime("%Y/%m/%d")